/* tslint:disable */
/* eslint-disable */
/**
 * Macellum
 * The Grocery Management System API is a robust and user-friendly interface designed to streamline and enhance grocery store operations. This API provides a comprehensive set of endpoints to manage essential tasks, including inventory management, order processing, customer interactions, and sales tracking. 
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: mail@alexandrelamberty.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

